name: Build Kernel A10s

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex libssl-dev \
            libelf-dev zip wget git python3 gcc-aarch64-linux-gnu

      - name: Download Clang 11
        run: |
          git clone --depth=1 https://github.com/samsung-mt6765-devs/clang_11.x.git $HOME/clang
          ls $HOME/clang

      - name: Build kernel
        run: |
          export ARCH=arm64
          export PATH=$HOME/clang/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          make O=out samsung/a10s_defconfig
          make O=out -j$(nproc)

      - name: Upload Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz
          path: out/arch/arm64/boot/Image.gz