name: Add KernelSU
on: workflow_dispatch

permissions:
  contents: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add KernelSU
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
          rm -rf KernelSU/.git
          rm -f drivers/kernelsu
          cp -r KernelSU/kernel drivers/kernelsu
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Add KernelSU kernel files"
          git push